### ISSUE TITLE
Big transformations

### ISSUE THREAD

**Issue by cecton** [big-data-europe/mu-swarm-logger-service#15]
We've been working on having more features for the Swarm UI and we discussed about transforming this service.

At this point, this service get information from the Docker API and translates it almost "as it" to triples in the database. But now we would like to have more information about the Docker API and translate them to simpler data inside the database.

Which basically means I'm going to drop about all the triples and information that are registered to only keep the few that we need: network and labels (mostly, I think). Also the events will not be exactly container events but more general events based on labels. For example, when a container is created, it will generate a new type of event E that includes the labels of the containers. But when new labels will be added to a container, it will be the exact same event. So no more distinction of the container state.

@earthquakesan I don't know if you use this service for other services, we mostly use it in @fr0gs 's HTTP Logger service and we are going to add it to the Swarm UI where we gonna need more the Docker stats (that I will probably translate to something simpler).

Best

**Comment by fr0gs** [comment]
I am not sure that dropping all the events besides network and labels is what we want. Docker events contain useful information such as memory and cpu% used at any given moment if I am not wrong right? 
I recall there can be a future need of querying for this information in the HTTP logger (or another service) to also paint statistics and visualize containers' data, not only the traffic they generate.

**Comment by earthquakesan** [comment]
You could simply filter events by "network" event type as we discussed here #9 (correctly me if I am wrong).

I do not like dropping the information as idea was to have a generic library, which could possibly be reused inside other projects (not only Swarm UI). This is not a submodule of Swarm UI.

**Comment by cecton** [comment]
Yes it will be more specific to BDE stack and not just a copy-paste of whatever is in Docker's API. So somehow it stays generic but to BDE.

The idea is that the BDE services will have directly usable information from the database and not generic stuff about Docker itself.

@fr0gs yes of course we will keep container stats but in a simplified manner. Right now we have the charge per CPU for example... I don't think every frontend want to handle that kind of information.

**Comment by cecton** [comment]
Closed for now because apparently we can't modify the labels of a running container. So any change now would just add more work for no feature nor any bug fix.
