### ISSUE TITLE
Unrecognized event logger message is incorrect

### ISSUE THREAD

**Issue by earthquakesan** [big-data-europe/mu-swarm-logger-service#8]
Logger message in [events.py](https://github.com/big-data-europe/mu-swarm-logger-service/blob/master/muswarmlogger/events.py#L69) is incorrect as event type was indeed recognized, but it is "Not supported".

**Comment by cecton** [comment]
I'm failing to see your point XD but if you really want to, you can make a PR to fix that.

To me "not recognized" is from the point of view of the application so it sounds right.
